name: Build PR Preview
on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write
  checks: write
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch 🛎️
        uses: actions/checkout@v3
      - name: Checkout Main Branch 🛎️
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
          clean: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build and Instrument Main Branch 🔧
        run: |
          cd main
          npm i
          npm ci --include=dev
          npm run build
          npm run style
          cd ..
          MAIN_BENCH=$(npm -s run benchmark_action -- main/dist/style.json)
          echo "MAIN_BENCH<<EOF" >> $GITHUB_ENV
          echo -e "$MAIN_BENCH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          MAIN_STATS=$(npm -s run stats_action -- main/dist/style.json)
          echo "MAIN_STATS<<EOF" >> $GITHUB_ENV
          echo -e "$MAIN_STATS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm -rf main
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo "Saved PR# ${{ github.event.pull_request.number }} for upload"
      - name: Save PR#
        uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
      - name: Install and Build 🔧
        run: |
          npm ci --include=dev
          npm run build
          npm run style
          npm run shields
          cp src/configs/config.aws.js src/config.js
      - name: Capture PR branch usage statistics
        id: pr-stats
        run: |
          PR_STATS=$(npm -s run stats_action -- dist/style.json)
          echo "PR_STATS<<EOF" >> $GITHUB_ENV
          echo -e "$PR_STATS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Capture PR branch benchmark
        id: pr-benchmark
        run: |
          PR_BENCH=$(npm -s run benchmark_action -- dist/style.json)
          echo "PR_BENCH<<EOF" >> $GITHUB_ENV
          echo -e "$PR_BENCH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Compare Stats
        id: compare-stats
        run: |
          mkdir stats
          echo '${{ env.MAIN_STATS }}'
          echo '${{ env.PR_STATS }}'
          node scripts/stats_compare '${{ env.MAIN_STATS }}' '${{ env.PR_STATS }}' > stats/stats-difference.md
      - name: Compare Benchmarks
        id: compare-benchmarks
        run: |
          echo '${{ env.MAIN_BENCH }}'
          echo '${{ env.PR_BENCH }}'
          node scripts/stats_compare '${{ env.MAIN_BENCH }}' '${{ env.PR_BENCH }}' > stats/bench-difference.md
      - name: Print Stats to GitHub Checks
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Performance Metrics
          conclusion: neutral
          output: |
            {"summary":"Style size changes introduced by this PR"}
          output_text_description_file: stats/stats-difference.md
      - name: Print Benchmarks to GitHub Checks
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Performance Benchmarks
          conclusion: neutral
          output: |
            {"summary":"Performance changes introduced by this PR"}
          output_text_description_file: stats/bench-difference.md
      - name: Upload Build artifact
        uses: actions/upload-artifact@v3
        with:
          name: americana
          path: dist/
